In [1]:
import pandas as pd
import numpy as np

# Load Dataset

In [2]:
ctrl = pd.read_csv('new_ctrl.csv')
gpt = pd.read_csv('new_gpt.csv')
gpt2 = pd.read_csv('new_gpt2.csv')
gpt3 = pd.read_csv('new_gpt3.csv')
instructgpt = pd.read_csv('new_instructgpt.csv')
grover = pd.read_csv('new_grover.csv')
xlm = pd.read_csv('new_xlm.csv')
xlnet = pd.read_csv('new_xlnet.csv')

pplm = pd.read_csv('new_pplm.csv')
human = pd.read_csv('new_human.csv')
fair = pd.read_csv('new_fair.csv')

In [3]:
ctrl.columns

Index(['Unnamed: 0', 'Generation', 'label'], dtype='object')

# Data Preparation 

In [4]:
random_binary_t2 = pd.concat([human.sample(1066), ctrl.sample(1066), gpt.sample(1066), gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), grover.sample(1066), 
                              xlm.sample(1066), xlnet.sample(1066), pplm.sample(1066), fair.sample(1066), ctrl.sample(1066), 
                              gpt.sample(1066), gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), grover.sample(1066), xlm.sample(1066), xlnet.sample(1066), 
                              pplm.sample(1066), fair.sample(1066), human.sample(1066), ctrl.sample(1066), human.sample(1066), 
                              gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), gpt.sample(1066), grover.sample(1066), xlm.sample(1066), xlnet.sample(1066), 
                              pplm.sample(1066), fair.sample(1066), human.sample(1066), ctrl.sample(1066), gpt.sample(1066), 
                              gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), grover.sample(1066), xlm.sample(1066), xlnet.sample(1066), pplm.sample(1066), 
                              fair.sample(1066), human.sample(1066), ctrl.sample(1066), gpt.sample(1066), gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), 
                              grover.sample(1066), xlm.sample(1066), xlnet.sample(1066), pplm.sample(1066), fair.sample(1066), 
                              human.sample(1066), ctrl.sample(1066), gpt.sample(1066), gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), grover.sample(1066), 
                              xlm.sample(1066), xlnet.sample(1066), pplm.sample(1066), fair.sample(1066), human.sample(1066), 
                              ctrl.sample(1066), gpt.sample(1066), gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), grover.sample(1066), xlm.sample(1066), xlnet.sample(1066), 
                              pplm.sample(1066), fair.sample(1066), human.sample(1066), ctrl.sample(1066), 
                          gpt.sample(1066), gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), grover.sample(1066), xlm.sample(1066), xlnet.sample(1066), pplm.sample(1066), 
                              fair.sample(1066), human.sample(1066), ctrl.sample(1066), gpt.sample(1066), gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), 
                              grover.sample(1066), xlm.sample(1066), xlnet.sample(1066), pplm.sample(1066), fair.sample(1066), ctrl.sample(1066), gpt.sample(1066), gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), grover.sample(1066), 
                              xlm.sample(1066), xlnet.sample(1066), pplm.sample(1066), fair.sample(1066), human.sample(1066), ctrl.sample(1066), gpt.sample(1066), gpt2.sample(1066), gpt3.sample(1066), instructgpt.sample(1066), grover.sample(1066), 
                              xlm.sample(1066), xlnet.sample(1066), pplm.sample(1066), fair.sample(1066), human.sample(1066)])

In [5]:
random_binary_t1 = pd.concat([human,human, human, human, human, human, human, human, human, human, human, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl,
                             ctrl, ctrl, ctrl, ctrl, ctrl, gpt, gpt, gpt, gpt, gpt, gpt, gpt, gpt, gpt, gpt, gpt, gpt2, gpt2, gpt2, gpt2, gpt2, gpt2,
                             gpt2, gpt2, gpt2, gpt2, gpt2, gpt3, gpt3, gpt3, gpt3, gpt3, gpt3, gpt3, gpt3, gpt3, gpt3, gpt3, instructgpt, instructgpt, instructgpt, instructgpt, instructgpt, instructgpt, instructgpt, instructgpt, instructgpt, instructgpt, instructgpt, grover, grover, grover, grover, grover, grover, grover, grover, grover, grover, grover, xlm, xlm, 
                             xlm, xlm, xlm, xlm, xlm, xlm, xlm, xlm, xlm, xlnet, xlnet, xlnet, xlnet, xlnet, xlnet, xlnet, xlnet, xlnet, xlnet, xlnet, 
                             pplm, pplm, pplm, pplm, pplm, pplm, pplm, pplm, pplm, pplm, pplm, fair, fair, fair, fair, fair, fair, fair, fair, fair, fair, fair])

In [6]:
len(random_binary_t1) == len(random_binary_t2)

True

In [7]:
len(random_binary_t1)

128986

In [8]:
random_binary_t2.head()

Unnamed: 0                                         Generation  label
61           61  Al Pacino hunts Nazis in 'Hunters,' a series w...  human
724         724  What it's like to be me by e. wes ely wes ely ...  human
498         498  Dutch government returns stolen 18th-century '...  human
454         454  Sleep anxiety and daylight saving time can exa...  human
636         636  Meet the 2019 CNN Hero of the Year (cnn) it's ...  human

In [9]:
new_label = [np.ones(len(human)), 
             np.zeros(10 * 1066), 
             np.ones(len(ctrl)), 
             np.zeros(13 * 1066), 
             np.ones(len(gpt)), 
             np.zeros(10 * 1066),
             np.ones(len(gpt2)),
             np.zeros(11 * 1066),
             np.ones(len(gpt3)),
             np.zeros(11 * 1066),
             np.ones(len(instructgpt)),
             np.zeros(11 * 1066),
             np.ones(len(grover)),
             np.zeros(11 * 1066),
             np.ones(len(xlm)),
             np.zeros(11 * 1066),
             np.ones(len(xlnet)),
             np.zeros(11 * 1066),
             np.ones(len(pplm)),
             np.zeros(11 * 1066),
             np.ones(len(fair))
            ]

In [10]:
flat_list = [item for sublist in new_label for item in sublist]

In [11]:
len(flat_list)

128986

In [12]:
len(random_binary_t1)

128986

In [13]:
len(random_binary_t2)

128986

In [14]:
binary_random = pd.DataFrame({'T1': list(random_binary_t1['Generation']), 'T2': list(random_binary_t2['Generation']), 'class': flat_list})

In [15]:
binary_random.to_csv('binary_random.csv')

# Create Balanced Dataset

In [16]:
balance_T1 = pd.concat([human.sample(1066), ctrl.sample(106), pplm.sample(106), gpt.sample(106), gpt2.sample(106), gpt3.sample(107), instructgpt.sample(107), grover.sample(107), 
                     xlm.sample(107), xlnet.sample(107), fair.sample(107), 
                       ctrl.sample(106), pplm.sample(106), gpt.sample(106), gpt2.sample(106), gpt3.sample(107), instructgpt.sample(107), grover.sample(107), 
                     xlm.sample(107), xlnet.sample(107), fair.sample(107), human.sample(1066)])
balance_T2 = pd.concat([human, human, ctrl.sample(106), pplm.sample(106), gpt.sample(106), gpt2.sample(106), gpt3.sample(107), instructgpt.sample(107), grover.sample(107), 
                     xlm.sample(107), xlnet.sample(107), fair.sample(107), 
                       ctrl.sample(106), pplm.sample(106), gpt.sample(106), gpt2.sample(106), gpt3.sample(107), instructgpt.sample(107), grover.sample(107), 
                     xlm.sample(107), xlnet.sample(107), fair.sample(107)])

In [17]:
balance_T2.head()

Unnamed: 0                                         Generation  label
0           0  Latest Headlines on CNN Business the great shu...  human
1           1  China wants to take a victory lap over its han...  human
2           2  Coronavirus disinformation creates challenges ...  human
3           3  China coronavirus: Eating wild animals made il...  human
4           4  China's economy could shrink for the first tim...  human

In [18]:
balance_label = [np.ones(1066),
                 np.zeros(1066), 
                 np.ones(1066), 
                np.zeros(1066)]

In [19]:
balance_label = [item for sublist in balance_label for item in sublist]


In [20]:
balanced_p1 = pd.DataFrame({'T1': list(balance_T1['Generation']), 'T2': list(balance_T2['Generation']), 'class': balance_label})

In [21]:
balanced_p1.to_csv('balanced_p1.csv')

In [ ]:
# !pip install fasttext

In [ ]:
# import fasttext

# # Define input file (text corpus) and output file (for the trained model)
# input_file = 'data.txt'
# output_file = 'model'

# # Train Skipgram word embeddings with FastText
# model = fasttext.train_unsupervised(input_file, model='skipgram', dim=100, epoch=5, lr=0.05, minCount=5)

# # Save the trained model to a file
# model.save_model(output_file + '.bin')

# # Load the trained model from the file
# loaded_model = fasttext.load_model(output_file + '.bin')

# # Get word embeddings for specific words
# word = 'example'
# word_vector = loaded_model.get_word_vector(word)
# print('Word vector for "{}":'.format(word), word_vector)

# # Find similar words based on cosine similarity
# similar_words = loaded_model.get_nearest_neighbors(word, k=10)
# print('Top 10 similar words to "{}":'.format(word), similar_words)

In [ ]:
# import tensorflow as tf
# from tensorflow.keras.layers import Input, SimpleRNN, Dense, Attention, Concatenate
# from tensorflow.keras.models import Model

# # Model configuration
# input_sequence_length = 100
# output_sequence_length = 100
# embedding_dim = 128
# rnn_units = 256

# # Encoder
# encoder_inputs = Input(shape=(input_sequence_length, embedding_dim), name="encoder_inputs")
# encoder_rnn = SimpleRNN(rnn_units, return_sequences=True, return_state=True, name="encoder_rnn")
# encoder_outputs, encoder_state = encoder_rnn(encoder_inputs)

# # Decoder
# decoder_inputs = Input(shape=(output_sequence_length, embedding_dim), name="decoder_inputs")
# decoder_rnn = SimpleRNN(rnn_units, return_sequences=True, return_state=True, name="decoder_rnn")
# decoder_outputs, _ = decoder_rnn(decoder_inputs, initial_state=encoder_state)

# # Attention
# attention_layer = Attention(name="attention_layer")
# attention_output = attention_layer([decoder_outputs, encoder_outputs])

# # Concatenate decoder outputs and attention output
# concat_layer = Concatenate(axis=-1, name="concat_layer")
# decoder_attention_concat = concat_layer([decoder_outputs, attention_output])

# # Dense layer for final output
# output_layer = Dense(embedding_dim, activation="softmax", name="output_layer")
# outputs = output_layer(decoder_attention_concat)

# # Model
# model = Model(inputs=[encoder_inputs, decoder_inputs], outputs=outputs)

# # Compile the model
# model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

# # Model summary
# model.summary()

# Random Binary Classification 

In [ ]:

import numpy as np
import pandas as pd 
from sklearn import metrics
import xgboost as xgb
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, f1_score
from sklearn import metrics

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix


In [ ]:
from yellowbrick.classifier import ClassPredictionError
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
def classify(data, label):
            
    data = data['T1'] + data['T2']
        
    X_train, X_test, y_train, y_test = train_test_split(data, label, stratify = label, test_size = 0.2, random_state = 1234)
    
    logistic_model = LogisticRegression()
    parameters = { 'C' : [0.01, 0.1, 1, 3, 10],
                   'penalty' : ['l2', 'elasticnet']
                 }

    cross_validation = 3
    scoring_metric = "f1"

#     clf = GridSearchCV(logistic_model,
#                                      parameters,
#                                      cv = cross_validation,
#                                      scoring = scoring_metric,
#                                      return_train_score=True)
    v = TfidfVectorizer()
    
    train_corpus = X_train
    test_corpus = X_test
    
    train_vector = v.fit_transform(train_corpus)
    test_vector = v.transform(test_corpus)
    
    
#     fit = clf.fit(train_vector,y_train)
#     print('Best Params ', clf.best_params_)
    parameters = { 'C' : 10,
               'penalty' : 'l2'
     }

    clf = LogisticRegression(C = parameters['C'], penalty = parameters['penalty'])
    fit = clf.fit(train_vector,y_train)
    pred = clf.predict(test_vector)
    
    
    Accuracy = accuracy_score(y_test,pred)
    F1 = f1_score(y_test, pred, average='macro')
    print("Accuracy:", Accuracy)
    print('F1:', F1)
    
    rec = recall_score(y_test, pred, average='macro')
    print('Recall: ', rec)
    prec = precision_score(y_test, pred, average='macro')
    print('Precision: ', prec)
    
    
    return y_test, pred

In [ ]:
balanced_p1.dropna(inplace=True)

In [ ]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

In [70]:
binary_random.dropna(inplace=True)

In [ ]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

In [ ]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

In [ ]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

In [ ]:
from sklearn.naive_bayes import BernoulliNB
def classify(data, label):
            
    data = data['T1'] + data['T2']
        
    X_train, X_test, y_train, y_test = train_test_split(data, label, stratify = label, test_size = 0.2, random_state = 1234)
    
    clf = BernoulliNB()    
    v = TfidfVectorizer()
    
    train_corpus = X_train
    test_corpus = X_test
    
    train_vector = v.fit_transform(train_corpus)
    test_vector = v.transform(test_corpus)
    
    
    fit = clf.fit(train_vector,y_train)
    pred = clf.predict(test_vector)
    
    
    Accuracy = accuracy_score(y_test,pred)
    F1 = f1_score(y_test, pred, average='macro')
    print("Accuracy:", Accuracy)
    print('F1:', F1)
    
    rec = recall_score(y_test, pred, average='macro')
    print('Recall: ', rec)
    prec = precision_score(y_test, pred, average='macro')
    print('Precision: ', prec)
    
    
    return y_test, pred

In [ ]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

In [ ]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

In [ ]:
def classify(data, label):
            
    data = data['T1'] + data['T2']
        
    X_train, X_test, y_train, y_test = train_test_split(data, label, stratify = label, test_size = 0.2, random_state = 1234)
    
    randomforest_model = RandomForestClassifier()

    parameters = { 'max_depth' : [10, 20, 30],
                   'n_estimators' : [90, 150, 180],
                   'max_samples' : [0.6, 0.8]
     }

    cross_validation = 3
    scoring_metric = "f1"
#     clf = GridSearchCV(randomforest_model, 
#                                          parameters,
#                                          cv = cross_validation,
#                                          scoring = scoring_metric,
#                                          return_train_score=True)
    v = TfidfVectorizer()
    
    train_corpus = X_train
    test_corpus = X_test
    
    train_vector = v.fit_transform(train_corpus)
    test_vector = v.transform(test_corpus)
    
    
#     fit = clf.fit(train_vector,y_train)
#     print('Best Params ', clf.best_params_)
    parameters = {
     'max_depth' : 30,
     'n_estimators' : 150,
     'max_samples' : 0.6
    }
    clf = RandomForestClassifier(max_depth = parameters['max_depth'],
                                            max_samples = parameters['max_samples'],
                                            n_estimators = parameters['n_estimators'])

    fit = clf.fit(train_vector,y_train)
    pred = clf.predict(test_vector)
    
    
    Accuracy = accuracy_score(y_test,pred)
    F1 = f1_score(y_test, pred, average='macro')
    print("Accuracy:", Accuracy)
    print('F1:', F1)
    
    rec = recall_score(y_test, pred, average='macro')
    print('Recall: ', rec)
    prec = precision_score(y_test, pred, average='macro')
    print('Precision: ', prec)
    
    
    return y_test, pred

In [ ]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

In [ ]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

In [ ]:
import xgboost
def classify(data, label):
            
    data = data['T1'] + data['T2']
        
    X_train, X_test, y_train, y_test = train_test_split(data, label, stratify = label, test_size = 0.2, random_state = 1234)
    
    xgboost_model = xgboost.XGBClassifier()

#     parameters = { 'max_depth' : [10, 20, 30],
#                    'n_estimators' : [90, 150, 180],
#                    'min_child_weight' : [1, 5, 10 ]
#      }

    cross_validation = 3
    scoring_metric = "f1"
#     clf = GridSearchCV(xgboost_model, 
#                                     parameters,
#                                     cv = cross_validation,
#                                     scoring = scoring_metric,
#                                     return_train_score=True)

    v = TfidfVectorizer()
    
    train_corpus = X_train
    test_corpus = X_test
    
    train_vector = v.fit_transform(train_corpus)
    test_vector = v.transform(test_corpus)
    
    
#     fit = clf.fit(train_vector,y_train)
#     print('Best Params ', clf.best_params_)
    parameters = { 'max_depth' : 20,
                   'min_child_weight' : 5,
                   'n_estimators' : 180
     }

    clf = xgboost.XGBClassifier(max_depth = parameters['max_depth'],
                                          min_child_weight = parameters['min_child_weight'],
                                          n_estimators = parameters['n_estimators'])

    fit = clf.fit(train_vector,y_train)
    pred = clf.predict(test_vector)
    
    
    Accuracy = accuracy_score(y_test,pred)
    F1 = f1_score(y_test, pred, average='macro')
    print("Accuracy:", Accuracy)
    print('F1:', F1)
    
    rec = recall_score(y_test, pred, average='macro')
    print('Recall: ', rec)
    prec = precision_score(y_test, pred, average='macro')
    print('Precision: ', prec)
    
    
    return y_test, pred

In [68]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

Accuracy: 0.634232121922626
F1: 0.6337483898668956
Recall:  0.6341903882310255
Precision:  0.6348799814335919


(2166    1.0
 4236    0.0
 2002    0.0
 512     1.0
 3241    0.0
        ... 
 747     1.0
 535     1.0
 311     1.0
 750     1.0
 2122    0.0
 Name: class, Length: 853, dtype: float64,
 array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,


In [71]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

Accuracy: 0.9255108767303889
F1: 0.6782046559182194
Recall:  0.6299710781969565
Precision:  0.8419981418086167


(99756     0.0
 13680     0.0
 693       1.0
 53068     0.0
 114921    0.0
          ... 
 123459    0.0
 85061     0.0
 126883    0.0
 106214    0.0
 10654     0.0
 Name: class, Length: 25789, dtype: float64,
 array([0, 0, 0, ..., 0, 0, 0]))

In [75]:
from sklearn.svm import SVC
def classify(data, label):
            
    data = data['T1'] + data['T2']
        
    X_train, X_test, y_train, y_test = train_test_split(data, label, stratify = label, test_size = 0.2, random_state = 1234)
    
    svm_model = SVC()

    parameters = { 'kernel' : ['poly', 'rbf', 'sigmoid'],
                   'max_iter' : [20, 50, 100]
     }

    cross_validation = 3
    scoring_metric = "f1"
    clf = GridSearchCV(svm_model, 
                                parameters,
                                cv = cross_validation,
                                scoring = scoring_metric,
                                return_train_score=True)

    v = TfidfVectorizer()
    
    train_corpus = X_train
    test_corpus = X_test
    
    train_vector = v.fit_transform(train_corpus)
    test_vector = v.transform(test_corpus)
    
    
    fit = clf.fit(train_vector,y_train)
    print('Best Params ', clf.best_params_)
#     parameters = {
#          'kernel' : 'sigmoid',
#          'max_iter' : 50,
#         }

#     clf = SVC(kernel = parameters['kernel'],
#     max_iter = parameters['max_iter'], probability = True)
#     fit = clf.fit(train_vector,y_train)
#     pred = clf.predict(test_vector)
    
    
#     Accuracy = accuracy_score(y_test,pred)
#     F1 = f1_score(y_test, pred, average='macro')
#     print("Accuracy:", Accuracy)
#     print('F1:', F1)
    
#     rec = recall_score(y_test, pred, average='macro')
#     print('Recall: ', rec)
#     prec = precision_score(y_test, pred, average='macro')
#     print('Precision: ', prec)
    
    
#     return y_test, pred

In [76]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\svm\_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=20).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\svm\_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=20).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\svm\_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=20).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\svm\_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=50).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\svm\_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=50).  Con

Best Params  {'kernel': 'sigmoid', 'max_iter': 100}


C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\svm\_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


In [74]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\svm\_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=50).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy: 0.8978246539222149
F1: 0.4812687281363775
Recall:  0.4980176354942982
Precision:  0.487224129216415


(99756     0.0
 13680     0.0
 693       1.0
 53068     0.0
 114921    0.0
          ... 
 123459    0.0
 85061     0.0
 126883    0.0
 106214    0.0
 10654     0.0
 Name: class, Length: 25789, dtype: float64,
 array([0., 0., 0., ..., 0., 0., 0.]))

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
def classify(data, label):
            
    data = data['T1'] + data['T2']
        
    X_train, X_test, y_train, y_test = train_test_split(data, label, stratify = label, test_size = 0.2, random_state = 1234)
    
    logistic_model = LogisticRegression()
    parameters = { 'C' : [0.01, 0.1, 1, 3, 10],
                   'penalty' : ['l2', 'elasticnet']
                 }

    cross_validation = 3
    scoring_metric = "f1"

#     clf = GridSearchCV(logistic_model,
#                                      parameters,
#                                      cv = cross_validation,
#                                      scoring = scoring_metric,
#                                      return_train_score=True)
    v = TfidfVectorizer()
    
    train_corpus = X_train
    test_corpus = X_test
    
    train_vector = v.fit_transform(train_corpus)
    test_vector = v.transform(test_corpus)
    
    
#     fit = clf.fit(train_vector,y_train)
#     print('Best Params ', clf.best_params_)
    parameters = { 'C' : 0.01,
               'penalty' : 'l2'
     }

    clf = LogisticRegression(C = parameters['C'], penalty = parameters['penalty'])
    fit = clf.fit(train_vector,y_train)
    pred = clf.predict(test_vector)
    
    
    Accuracy = accuracy_score(y_test,pred)
    F1 = f1_score(y_test, pred, average='macro')
    print("Accuracy:", Accuracy)
    print('F1:', F1)
    
    rec = recall_score(y_test, pred, average='macro')
    print('Recall: ', rec)
    prec = precision_score(y_test, pred, average='macro')
    print('Precision: ', prec)
    
    
    return y_test, pred

In [28]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Best Params  {'C': 0.01, 'penalty': 'l2'}


In [31]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

Accuracy: 0.8888824551244934
F1: 0.470586432052972
Recall:  0.5
Precision:  0.4444412275622467


C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(2269     0.0
 29062    0.0
 21144    0.0
 64101    1.0
 46390    0.0
         ... 
 46736    0.0
 47506    0.0
 49566    0.0
 186      1.0
 6185     0.0
 Name: class, Length: 17270, dtype: float64,
 array([0., 0., 0., ..., 0., 0., 0.]))

In [63]:
from sklearn.svm import SVC
def classify(data, label):
            
    data = data['T1'] + data['T2']
        
    X_train, X_test, y_train, y_test = train_test_split(data, label, stratify = label, test_size = 0.2, random_state = 1234)
    
    svm_model = SVC()

    parameters = { 'kernel' : ['poly', 'rbf', 'sigmoid'],
                   'max_iter' : [20, 50, 100]
     }

    cross_validation = 3
    scoring_metric = "f1"
#     clf = GridSearchCV(svm_model, 
#                                 parameters,
#                                 cv = cross_validation,
#                                 scoring = scoring_metric,
#                                 return_train_score=True)

    v = TfidfVectorizer()
    
    train_corpus = X_train
    test_corpus = X_test
    
    train_vector = v.fit_transform(train_corpus)
    test_vector = v.transform(test_corpus)
    
    
#     fit = clf.fit(train_vector,y_train)
#     print('Best Params ', clf.best_params_)
    parameters = {
         'kernel' : 'sigmoid',
         'max_iter' : 50,
        }

    clf = SVC(kernel = parameters['kernel'],
    max_iter = parameters['max_iter'], probability = True)
    fit = clf.fit(train_vector,y_train)
    pred = clf.predict(test_vector)
    
    
    Accuracy = accuracy_score(y_test,pred)
    F1 = f1_score(y_test, pred, average='macro')
    print("Accuracy:", Accuracy)
    print('F1:', F1)
    
    rec = recall_score(y_test, pred, average='macro')
    print('Recall: ', rec)
    prec = precision_score(y_test, pred, average='macro')
    print('Precision: ', prec)
    
    
    return y_test, pred

In [57]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\svm\_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy: 0.5205158264947245
F1: 0.4568697506791522
Recall:  0.5209178568679839
Precision:  0.5394930770348536


(2166    1.0
 4236    0.0
 2001    0.0
 512     1.0
 3240    0.0
        ... 
 747     1.0
 535     1.0
 311     1.0
 750     1.0
 2121    0.0
 Name: class, Length: 853, dtype: float64,
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.

In [64]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

C:\Users\gdhir\anaconda3\lib\site-packages\sklearn\svm\_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=50).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Accuracy: 0.7527504342790967
F1: 0.49311776678147934
Recall:  0.49637916899493656
Precision:  0.4975024988591847


(2269     0.0
 29062    0.0
 21144    0.0
 64101    1.0
 46390    0.0
         ... 
 46736    0.0
 47506    0.0
 49566    0.0
 186      1.0
 6185     0.0
 Name: class, Length: 17270, dtype: float64,
 array([1., 0., 0., ..., 1., 0., 0.]))

In [65]:
from sklearn.naive_bayes import BernoulliNB
def classify(data, label):
            
    data = data['T1'] + data['T2']
        
    X_train, X_test, y_train, y_test = train_test_split(data, label, stratify = label, test_size = 0.2, random_state = 1234)
    
    clf = BernoulliNB()    
    v = TfidfVectorizer()
    
    train_corpus = X_train
    test_corpus = X_test
    
    train_vector = v.fit_transform(train_corpus)
    test_vector = v.transform(test_corpus)
    
    
    fit = clf.fit(train_vector,y_train)
    pred = clf.predict(test_vector)
    
    
    Accuracy = accuracy_score(y_test,pred)
    F1 = f1_score(y_test, pred, average='macro')
    print("Accuracy:", Accuracy)
    print('F1:', F1)
    
    rec = recall_score(y_test, pred, average='macro')
    print('Recall: ', rec)
    prec = precision_score(y_test, pred, average='macro')
    print('Precision: ', prec)
    
    
    return y_test, pred

In [66]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

Accuracy: 0.36107854630715125
F1: 0.35699219209250543
Recall:  0.36098558564501765
Precision:  0.3574143200297723


(2166    1.0
 4236    0.0
 2001    0.0
 512     1.0
 3240    0.0
        ... 
 747     1.0
 535     1.0
 311     1.0
 750     1.0
 2121    0.0
 Name: class, Length: 853, dtype: float64,
 array([0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
        1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
        1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0.,
        1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
        1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0.,
        0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1.,
        0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1.,
        1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
        1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1.,
        1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.

In [67]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

Accuracy: 0.6357845975680371
F1: 0.47428519913370065
Recall:  0.5181301915921306
Precision:  0.5080427305831513


(2269     0.0
 29062    0.0
 21144    0.0
 64101    1.0
 46390    0.0
         ... 
 46736    0.0
 47506    0.0
 49566    0.0
 186      1.0
 6185     0.0
 Name: class, Length: 17270, dtype: float64,
 array([0., 1., 0., ..., 0., 1., 0.]))

In [74]:
def classify(data, label):
            
    data = data['T1'] + data['T2']
        
    X_train, X_test, y_train, y_test = train_test_split(data, label, stratify = label, test_size = 0.2, random_state = 1234)
    
    randomforest_model = RandomForestClassifier()

    parameters = { 'max_depth' : [10, 20, 30],
                   'n_estimators' : [90, 150, 180],
                   'max_samples' : [0.6, 0.8]
     }

    cross_validation = 3
    scoring_metric = "f1"
#     clf = GridSearchCV(randomforest_model, 
#                                          parameters,
#                                          cv = cross_validation,
#                                          scoring = scoring_metric,
#                                          return_train_score=True)
    v = TfidfVectorizer()
    
    train_corpus = X_train
    test_corpus = X_test
    
    train_vector = v.fit_transform(train_corpus)
    test_vector = v.transform(test_corpus)
    
    
#     fit = clf.fit(train_vector,y_train)
#     print('Best Params ', clf.best_params_)
    parameters = {
     'max_depth' : 30,
     'n_estimators' : 90,
     'max_samples' : 0.8
    }
    clf = RandomForestClassifier(max_depth = parameters['max_depth'],
                                            max_samples = parameters['max_samples'],
                                            n_estimators = parameters['n_estimators'])

    fit = clf.fit(train_vector,y_train)
    pred = clf.predict(test_vector)
    
    
    Accuracy = accuracy_score(y_test,pred)
    F1 = f1_score(y_test, pred, average='macro')
    print("Accuracy:", Accuracy)
    print('F1:', F1)
    
    rec = recall_score(y_test, pred, average='macro')
    print('Recall: ', rec)
    prec = precision_score(y_test, pred, average='macro')
    print('Precision: ', prec)
    
    
    return y_test, pred

In [71]:
classify(balanced_p1[['T1', 'T2']], balanced_p1['class'])

Accuracy: 0.5803048065650644
F1: 0.5802350004398698
Recall:  0.5802904860859144
Precision:  0.5803390688259109


(2166    1.0
 4236    0.0
 2001    0.0
 512     1.0
 3240    0.0
        ... 
 747     1.0
 535     1.0
 311     1.0
 750     1.0
 2121    0.0
 Name: class, Length: 853, dtype: float64,
 array([1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
        1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
        0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1.,
        0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1.,
        0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1.,
        1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
        0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1.

In [75]:
classify(binary_random[['T1', 'T2']], binary_random['class'])

Accuracy: 0.8995367689635205
F1: 0.5611401864573291
Recall:  0.5481696174719145
Precision:  0.9465625889029036


(2269     0.0
 29062    0.0
 21144    0.0
 64101    1.0
 46390    0.0
         ... 
 46736    0.0
 47506    0.0
 49566    0.0
 186      1.0
 6185     0.0
 Name: class, Length: 17270, dtype: float64,
 array([0., 0., 0., ..., 0., 0., 0.]))

In [76]:
import tabulate
print('Task P1: Balanced')
conclusion = [['Model', 'Accuracy', 'Precision', 'Recall', 'F1 Score',],
             ['Logistic Regression', 50.2, 50.2, 50.2, 49.8],
             ['Random Forest Classifier', 58.0, 58.0, 58.0, 58.0],
             ['XGBoost Classifier',  69.9, 69.9, 69.9, 69.9],
              ['Naive Bayes Classifier',  36.1, 35.7, 36.1, 35.7],
              ['SVM Classifier',  52, 53.9, 52.1, 45.7],
             ]
print(tabulate.tabulate(conclusion, tablefmt='fancy_grid'))

Task P1: Balanced
╒══════════════════════════╤══════════╤═══════════╤════════╤══════════╕
│ Model                    │ Accuracy │ Precision │ Recall │ F1 Score │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ Logistic Regression      │ 50.2     │ 50.2      │ 50.2   │ 49.8     │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ Random Forest Classifier │ 58.0     │ 58.0      │ 58.0   │ 58.0     │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ XGBoost Classifier       │ 69.9     │ 69.9      │ 69.9   │ 69.9     │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ Naive Bayes Classifier   │ 36.1     │ 35.7      │ 36.1   │ 35.7     │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ SVM Classifier           │ 52       │ 53.9      │ 52.1   │ 45.7     │
╘══════════════════════════╧══════════╧═══════════╧════════╧══════════╛


In [77]:
import tabulate
print('Task P1: Binary Random')
conclusion = [['Model', 'Accuracy', 'Precision', 'Recall', 'F1 Score',],
             ['Logistic Regression', 88.9, 44.4, 50, 47],
             ['Random Forest Classifier', 89.9, 94.6, 54.8, 56.1],
             ['XGBoost Classifier',  92.7, 91.4, 69.2, 75.2],
              ['Naive Bayes Classifier',  63.6, 50.8, 51.8, 47.4],
              ['SVM Classifier',  75.3, 49.8, 49.6, 49.3],
             ]
print(tabulate.tabulate(conclusion, tablefmt='fancy_grid'))

Task P1: Binary Random
╒══════════════════════════╤══════════╤═══════════╤════════╤══════════╕
│ Model                    │ Accuracy │ Precision │ Recall │ F1 Score │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ Logistic Regression      │ 88.9     │ 44.4      │ 50     │ 47       │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ Random Forest Classifier │ 89.9     │ 94.6      │ 54.8   │ 56.1     │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ XGBoost Classifier       │ 92.7     │ 91.4      │ 69.2   │ 75.2     │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ Naive Bayes Classifier   │ 63.6     │ 50.8      │ 51.8   │ 47.4     │
├──────────────────────────┼──────────┼───────────┼────────┼──────────┤
│ SVM Classifier           │ 75.3     │ 49.8      │ 49.6   │ 49.3     │
╘══════════════════════════╧══════════╧═══════════╧════════╧══════════╛


In [ ]:
Accuracy: 0.8995367689635205
F1: 0.5611401864573291
Recall:  0.5481696174719145
Precision:  0.9465625889029036