In [ ]:
#BEGIN

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!ls

Mounted at /content/drive
drive  sample_data


In [ ]:
!pip install simpletransformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.7/250.7 kB 21.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 90.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.6/474.6 kB 43.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 6.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 86.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 97.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 113.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 86.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 29.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 26.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.3/203.3 kB 2

In [ ]:
# General
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import itertools
from pandas import DataFrame

# Visualization
import matplotlib.font_manager as fm
from matplotlib.collections import QuadMesh
import seaborn as sn
import plotly.express as px

# Feature extraction approach
from sklearn.feature_extraction.text import TfidfVectorizer
from string import punctuation
from nltk.stem import PorterStemmer 
from nltk.tokenize import word_tokenize 
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')

# Classification
import xgboost as xgb
import lightgbm as lgbm
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from simpletransformers.classification import ClassificationModel
import torch

# Parallelize apply on Pandas
!pip install pandarallel
from pandarallel import pandarallel
pandarallel.initialize()

# Evaluation
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix 
from sklearn.svm import SVC
from sklearn.naive_bayes import BernoulliNB

import nltk
from nltk.util import ngrams
from collections import Counter
import heapq

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for pandarallel: filename=pandarallel-1.6.5-py3-none-any.whl size=16677 sha256=63da04eaf292216e43ebbb6ea6c1bcb3525ddceb164824fe2226205e406270df
  Stored in directory: /root/.cache/pip/wheels/50/4f/1e/34e057bb868842209f1623f195b74fd7eda229308a7352d47f
Successfully built pandarallel
INFO: Pandarallel will run on 1 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.


In [ ]:
# path  = '/content/drive/My Drive/CS_635/temp/'
path  = '/content/gdrive/MyDrive/'

In [ ]:
# train = pd.read_csv(path+'train_att1.csv')
# test = pd.read_csv(path+'test_att1.csv')
# val = pd.read_csv(path+'val_att1.csv')

In [ ]:
# train = train.drop(['Unnamed: 0'], axis=1)
# test = test.drop(['Unnamed: 0'], axis=1)
# val = val.drop(['Unnamed: 0'], axis=1)

In [ ]:
# def label_change(data):
#     for i in range(len(data)):
#         if data['label'][i] == 'HUMAN':
#             data['label'][i] = 0
#         elif data['label'][i] == 'GROVER':
#             data['label'][i] = 1
#         elif data['label'][i] == 'GPT2':
#             data['label'][i] = 2
#         elif data['label'][i] == 'GPT-j-6B':
#             data['label'][i] = 3
#     return data

# import re
# def clean_df(df):
#     for i in range(len(df)):
#         df['text'].loc[i] = re.sub('\s+', ' ', df['text'].iloc[i])
#     return df

In [ ]:
# def label_change(data):
#     for i in range(len(data)):
#         if data['label'][i] == 'HUMAN':
#             data['label'][i] = 0
#         elif data['label'][i] == 'GROVER':
#             data['label'][i] = 1
#         elif data['label'][i] == 'GPT2':
#             data['label'][i] = 2
#         elif data['label'][i] == 'GPT-j-6B':
#             data['label'][i] = 3
#     return data

In [ ]:
drive.mount('/content/gdrive/', force_remount=True)

data_dir = '/content/gdrive/MyDrive'
filename = 'balanced_p1.csv'
# test_filename = 'p2_test.csv'
!cp $data_dir/$filename .

Mounted at /content/gdrive/


In [ ]:
# data = pd.read_csv(path+'p2_dataset.csv')
data1 = pd.read_csv(f'{data_dir}/{filename}')
# data2 = pd.read_csv(f'{data_dir}/{test_filename}')

In [ ]:
# train = label_change(train)
# test = label_change(test)
# val = label_change(val)

# train = clean_df(train)
# test = clean_df(test)
# val = clean_df(val)

In [ ]:
# Text pre-processing as required to compare the content of different authors
def fil_sent(sent):
    """
    Filter stopwords
    """
    filtered_sentence = ' '.join([w for w in sent.split() if not w in stop_words])
    filtered_sentence = ''.join([w for w in filtered_sentence if w not in list(punctuation)])
    filtered_sentence = filtered_sentence.strip()
    filtered_sentence = filtered_sentence.split()
    return filtered_sentence

def process(sent):
    """
    Apply stemming
    """
    sent = str(sent)
    return fil_sent(' '.join([ps.stem(str(x).lower()) for x in word_tokenize(sent)]))

stop_words = set(stopwords.words('english'))
ps = PorterStemmer() 

In [ ]:
# Similarity between two authors' content
def jaccard_similarity(list1, list2):

    list1 = list1[:512]
    list2 = list2[:512]
    
    intersection = len(list(set(list1).intersection(list2)))
    union = (len(list1) + len(list2)) - intersection

    if union > 0:
      return float(intersection) / union
    else:
      return 0

In [ ]:
# Computes the relative hardness
def rel_hardness(df, col_id, col_text):

  n_labels = len(list(set(df[col_text].values)))
  return 1/(n_labels * (n_labels - 1) * 0.5) * sum([jaccard_similarity(x[0], x[1]) for x in itertools.combinations(all_text_all_category(df, col_id, col_text), 2) if x[0] != x[1]])

In [ ]:
def fil_sent(sent):
  """
  Filter stopwords
  """

  filtered_sentence = ' '.join([w for w in sent.split() if not w in stop_words])
  return filtered_sentence

def process(sent):
  """
  Apply stemming
  """

  sent = str(sent)
  return fil_sent(' '.join([ps.stem(str(x).lower()) for x in word_tokenize(sent)]))

stop_words = set(stopwords.words('english'))
ps = PorterStemmer() 

def extract_style(text):
    """
    Extracting stylometric features of a text
    """

    text = str(text)
    len_text = len(text)
    len_words = len(text.split())
    avg_len = np.mean([len(t) for t in text.split()])
    num_short_w = len([t for t in text.split() if len(t) < 3])
    per_digit = sum(t.isdigit() for t in text)/len(text)
    per_cap = sum(1 for t in text if t.isupper())/len(text)
    f_a = sum(1 for t in text if t.lower() == "a")/len(text)
    f_b = sum(1 for t in text if t.lower() == "b")/len(text)
    f_c = sum(1 for t in text if t.lower() == "c")/len(text)
    f_d = sum(1 for t in text if t.lower() == "d")/len(text)
    f_e = sum(1 for t in text if t.lower() == "e")/len(text)
    f_f = sum(1 for t in text if t.lower() == "f")/len(text)
    f_g = sum(1 for t in text if t.lower() == "g")/len(text)
    f_h = sum(1 for t in text if t.lower() == "h")/len(text)
    f_i = sum(1 for t in text if t.lower() == "i")/len(text)
    f_j = sum(1 for t in text if t.lower() == "j")/len(text)
    f_k = sum(1 for t in text if t.lower() == "k")/len(text)
    f_l = sum(1 for t in text if t.lower() == "l")/len(text)
    f_m = sum(1 for t in text if t.lower() == "m")/len(text)
    f_n = sum(1 for t in text if t.lower() == "n")/len(text)
    f_o = sum(1 for t in text if t.lower() == "o")/len(text)
    f_p = sum(1 for t in text if t.lower() == "p")/len(text)
    f_q = sum(1 for t in text if t.lower() == "q")/len(text)
    f_r = sum(1 for t in text if t.lower() == "r")/len(text)
    f_s = sum(1 for t in text if t.lower() == "s")/len(text)
    f_t = sum(1 for t in text if t.lower() == "t")/len(text)
    f_u = sum(1 for t in text if t.lower() == "u")/len(text)
    f_v = sum(1 for t in text if t.lower() == "v")/len(text)
    f_w = sum(1 for t in text if t.lower() == "w")/len(text)
    f_x = sum(1 for t in text if t.lower() == "x")/len(text)
    f_y = sum(1 for t in text if t.lower() == "y")/len(text)
    f_z = sum(1 for t in text if t.lower() == "z")/len(text)
    f_1 = sum(1 for t in text if t.lower() == "1")/len(text)
    f_2 = sum(1 for t in text if t.lower() == "2")/len(text)
    f_3 = sum(1 for t in text if t.lower() == "3")/len(text)
    f_4 = sum(1 for t in text if t.lower() == "4")/len(text)
    f_5 = sum(1 for t in text if t.lower() == "5")/len(text)
    f_6 = sum(1 for t in text if t.lower() == "6")/len(text)
    f_7 = sum(1 for t in text if t.lower() == "7")/len(text)
    f_8 = sum(1 for t in text if t.lower() == "8")/len(text)
    f_9 = sum(1 for t in text if t.lower() == "9")/len(text)
    f_0 = sum(1 for t in text if t.lower() == "0")/len(text)
    f_e_0 = sum(1 for t in text if t.lower() == "!")/len(text)
    f_e_1 = sum(1 for t in text if t.lower() == "-")/len(text)
    f_e_2 = sum(1 for t in text if t.lower() == ":")/len(text)
    f_e_3 = sum(1 for t in text if t.lower() == "?")/len(text)
    f_e_4 = sum(1 for t in text if t.lower() == ".")/len(text)
    f_e_5 = sum(1 for t in text if t.lower() == ",")/len(text)
    f_e_6 = sum(1 for t in text if t.lower() == ";")/len(text)
    f_e_7 = sum(1 for t in text if t.lower() == "'")/len(text)
    f_e_8 = sum(1 for t in text if t.lower() == "/")/len(text)
    f_e_9 = sum(1 for t in text if t.lower() == "(")/len(text)
    f_e_10 = sum(1 for t in text if t.lower() == ")")/len(text)
    f_e_11 = sum(1 for t in text if t.lower() == "&")/len(text)
    richness = len(list(set(text.split())))/len(text.split())

    return pd.Series([avg_len, len_text, len_words, num_short_w, per_digit, per_cap, f_a, f_b, f_c, f_d, f_e, f_f, f_g, f_h, f_i, f_j, f_k, f_l, f_m, f_n, f_o, f_p, f_q, f_r, f_s, f_t, f_u, f_v, f_w, f_x, f_y, f_z, f_0, f_1, f_2, f_3, f_4, f_5, f_6, f_7, f_8, f_9, f_e_0, f_e_1, f_e_2, f_e_3, f_e_4, f_e_5, f_e_6, f_e_7, f_e_8, f_e_9, f_e_10, f_e_11, richness])

def return_best_bi_grams(text):
  bigrams = ngrams(text,2)

  data = dict(Counter(bigrams))
  list_ngrams = heapq.nlargest(100, data.keys(), key=lambda k: data[k])
  return list_ngrams

def return_best_tri_grams(text):
  trigrams = ngrams(text,3)

  data = dict(Counter(trigrams))
  list_ngrams = heapq.nlargest(100, data.keys(), key=lambda k: data[k])
  return list_ngrams

def find_freq_n_gram_in_txt(text, list_bigram, list_trigram):

  to_ret = []

  num_bigrams = len(Counter(zip(text,text[1:])))
  num_trigrams = len(Counter(zip(text,text[1:],text[2:])))

  for n_gram in list_bigram: 
      to_ret.append(text.count(''.join(n_gram))/num_bigrams)

  for n_gram in list_trigram: 
      to_ret.append(text.count(''.join(n_gram))/num_trigrams)

  return to_ret

In [ ]:
import nltk
nltk.download('universal_tagset')
nltk.download('averaged_perceptron_tagger')
from nltk import word_tokenize
def extract_pos(text):
  text = str(text)
  tokens = word_tokenize(text)
  tags = nltk.pos_tag(tokens, tagset = "universal")
  CC = sum(1 for word, tag in tags if tag == 'CC')/len(text),
  CD = sum(1 for word, tag in tags if tag == 'CD')/len(text),
  DT = sum(1 for word, tag in tags if tag == 'DT')/len(text),
  EX = sum(1 for word, tag in tags if tag == 'EX')/len(text),
  FW = sum(1 for word, tag in tags if tag == 'FW')/len(text),
  IN = sum(1 for word, tag in tags if tag == 'IN')/len(text),
  JJ = sum(1 for word, tag in tags if tag == 'JJ')/len(text),
  JJR = sum(1 for word, tag in tags if tag == 'JJR')/len(text),
  JJS = sum(1 for word, tag in tags if tag == 'JJS')/len(text),
  LS = sum(1 for word, tag in tags if tag == 'LS')/len(text),
  MD = sum(1 for word, tag in tags if tag == 'MD')/len(text),
  NN = sum(1 for word, tag in tags if tag == 'NN')/len(text),
  NNS = sum(1 for word, tag in tags if tag == 'NNS')/len(text),
  NNP = sum(1 for word, tag in tags if tag == 'NNP')/len(text),
  PDT = sum(1 for word, tag in tags if tag == 'PDT')/len(text),
  POS = sum(1 for word, tag in tags if tag == 'POS')/len(text),
  PRP = sum(1 for word, tag in tags if tag == 'PRP')/len(text),
  PRPs = sum(1 for word, tag in tags if tag == 'PRP$')/len(text),
  RB = sum(1 for word, tag in tags if tag == 'RB')/len(text),
  RBR = sum(1 for word, tag in tags if tag == 'RBR')/len(text),
  RBS = sum(1 for word, tag in tags if tag == 'RBS')/len(text),
  RP = sum(1 for word, tag in tags if tag == 'RP')/len(text),
  SYM = sum(1 for word, tag in tags if tag == 'SYM')/len(text),
  TO = sum(1 for word, tag in tags if tag == 'TO')/len(text),
  UH = sum(1 for word, tag in tags if tag == 'UH')/len(text),
  VB = sum(1 for word, tag in tags if tag == 'VB')/len(text),
  VBD = sum(1 for word, tag in tags if tag == 'VBD')/len(text),
  VBG = sum(1 for word, tag in tags if tag == 'VBG')/len(text),
  VBN = sum(1 for word, tag in tags if tag == 'VBN')/len(text),
  VBP = sum(1 for word, tag in tags if tag == 'VBP')/len(text),
  VBZ = sum(1 for word, tag in tags if tag == 'VBZ')/len(text),
  WDT = sum(1 for word, tag in tags if tag == 'WDT')/len(text),
  WP = sum(1 for word, tag in tags if tag == 'WP')/len(text),
  WPs = sum(1 for word, tag in tags if tag == 'WP$')/len(text),
  WRB = sum(1 for word, tag in tags if tag == 'WRB')/len(text),

  return pd.Series([CC[0], CD[0], DT[0], EX[0], FW[0], IN[0], JJ[0], JJR[0], JJS[0], LS[0], MD[0], NN[0], NNS[0], NNP[0], PDT[0], POS[0], PRP[0], PRPs[0], RB[0], RBR[0], RBS[0], RP[0], SYM[0], TO[0], UH[0], VB[0], VBD[0], VBG[0], VBN[0], VBP[0], VBZ[0], WDT[0], WP[0], WPs[0], WRB[0]])


  # return pd.Series([CC, CD, DT, EX, FW, IN, JJ, JJR, JJS, LS, MD, NN, NNS, NNP, PDT, POS, PRP, PRPs, RB, RBR, RBS, RP, SYM, TO, UH, VB, VBD, VBG, VBN, VBP, VBZ, WDT, WP, WPs, WRB])



[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Unzipping taggers/universal_tagset.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


In [ ]:
# import nltk
# from collections import Counter
# nltk.download('averaged_perceptron_tagger')
# nltk.download('universal_tagset')
# from nltk import word_tokenize
# text = 'This is a sentence'
# text = str(text)
# tokens = word_tokenize(text)
# tags = nltk.pos_tag(tokens, tagset = "universal")
# d = Counter(tags)


In [ ]:
# len(tags)

In [ ]:
# df = pd.concat([train, test, val])
df = pd.concat([data1])
df['text_tfidf'] = df['T1'].parallel_apply(lambda x: process(x))
df[["avg_len", "len_text", "len_words", "num_short_w", "per_digit", "per_cap", "f_a", "f_b", "f_c", "f_d", "f_e", "f_f", "f_g", "f_h", "f_i", "f_j", "f_k", "f_l", "f_m", "f_n", "f_o", "f_p", "f_q", "f_r", "f_s", "f_t", "f_u", "f_v", "f_w", "f_x", "f_y", "f_z", "f_0", "f_1", "f_2", "f_3", "f_4", "f_5", "f_6", "f_7", "f_8", "f_9",  "f_e_0", "f_e_1", "f_e_2", "f_e_3", "f_e_4", "f_e_5", "f_e_6", "f_e_7", "f_e_8", "f_e_9", "f_e_10", "f_e_11", "richness"]] = df['T1'].parallel_apply(lambda x: extract_style(x))
df['text_tfidf'] = df['T2'].parallel_apply(lambda x: process(x))
df[["avg_len", "len_text", "len_words", "num_short_w", "per_digit", "per_cap", "f_a", "f_b", "f_c", "f_d", "f_e", "f_f", "f_g", "f_h", "f_i", "f_j", "f_k", "f_l", "f_m", "f_n", "f_o", "f_p", "f_q", "f_r", "f_s", "f_t", "f_u", "f_v", "f_w", "f_x", "f_y", "f_z", "f_0", "f_1", "f_2", "f_3", "f_4", "f_5", "f_6", "f_7", "f_8", "f_9",  "f_e_0", "f_e_1", "f_e_2", "f_e_3", "f_e_4", "f_e_5", "f_e_6", "f_e_7", "f_e_8", "f_e_9", "f_e_10", "f_e_11", "richness"]] = df['T2'].parallel_apply(lambda x: extract_style(x))
# df[['CC', 'CD', 'DT', 'EX', 'FW', 'IN', 'JJ', 'JJR', 'JJS', 'LS', 'MD', 'NN', 'NNS', 'NNP', 'PDT', 'POS', 'PRP', 'PRPs', 'RB', 'RBR', 'RBS', 'RP', 'SYM', 'TO', 'UH', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 'WDT', 'WP', 'WPs', 'WRB']] = df['text'].parallel_apply(lambda x: extract_pos(x))

In [ ]:
# df[['CC', 'CD', 'DT', 'EX', 'FW', 'IN', 'JJ', 'JJR', 'JJS', 'LS', 'MD', 'NN', 'NNS', 'NNP', 'PDT', 'POS', 'PRP', 'PRPs', 'RB', 'RBR', 'RBS', 'RP', 'SYM', 'TO', 'UH', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 'WDT', 'WP', 'WPs', 'WRB']] = df['text'].parallel_apply(lambda x: extract_pos(x))

In [ ]:
## Heading

In [ ]:
df

Unnamed: 0                                                 T1  \
0              0  Super Tuesday: BBC finds Bloomberg campaign of...   
1              1                             Newsbeat have your say   
2              2  Worst-Case Estimates for U.S. Coronavirus Deat...   
3              3  Latest Headlines on CNN Business the great shu...   
4              4  Pentagon Asks to Reconsider Awarding Huge Clou...   
...          ...                                                ...   
4259        4259  Will warmer weather help fight the coronavirus...   
4260        4260  Iran to temporarily free 54,000 prisoners as c...   
4261        4261  An Australian man dies in alleged ax attack ne...   
4262        4262  Here's what Trump's coronavirus emergency decl...   
4263        4263  How architect Mariam Kamara is masterminding a...   

                                                     T2  class  \
0     Latest Headlines on CNN Business the great shu...    1.0   
1     China wants to take a victory lap over its han...    1.0   
2     Coronavirus disinformation creates challenges ...    1.0   
3     China coronavirus: Eating wild animals made il...    1.0   
4     China's economy could shrink for the first tim...    1.0   
...                                                 ...    ...   
4259  why the black press is more relevant than ever...    0.0   
4260  fish oil supplements linked to lower risk of h...    0.0   
4261  expert view: seven leading african photographe...    0.0   
4262  players react to ncaa canceling march madness ...    0.0   
4263  saudi arabia detains senior members of its roy...    0.0   

                                             text_tfidf   avg_len  len_text  \
0     latest headlin cnn busi great shutdown 2020 : ...  5.352941     107.0   
1     china want take victori lap handl coronaviru o...  5.071491    6963.0   
2     coronaviru disinform creat challeng china 's g...  5.089168    9218.0   
3     china coronaviru : eat wild anim made illeg en...  5.052421   12122.0   
4     china 's economi could shrink first time decad...  5.137004    4792.0   
...                                                 ...       ...       ...   
4259  whi black press relev ever global affair black...  4.600467    2396.0   
4260  fish oil supplement link lower risk heart dise...  4.668407    2170.0   
4261  expert view : seven lead african photograph ac...  4.565934    2025.0   
4262  player react ncaa cancel march mad amid corona...  4.808786    2247.0   
4263  saudi arabia detain senior member royal famili...  5.017544    2400.0   

      len_words  num_short_w  per_digit  ...     f_e_3     f_e_4     f_e_5  \
0          17.0          2.0   0.037383  ...  0.000000  0.000000  0.000000   
1        1147.0        225.0   0.002011  ...  0.000000  0.005170  0.009335   
2        1514.0        285.0   0.003146  ...  0.000325  0.006075  0.008679   
3        2003.0        359.0   0.007342  ...  0.000495  0.007754  0.007837   
4         781.0        133.0   0.010643  ...  0.000000  0.007304  0.007095   
...         ...          ...        ...  ...       ...       ...       ...   
4259      428.0         86.0   0.002087  ...  0.000000  0.010851  0.007513   
4260      383.0         71.0   0.006452  ...  0.000000  0.006912  0.010138   
4261      364.0        126.0   0.078519  ...  0.000494  0.001481  0.033580   
4262      387.0         65.0   0.006231  ...  0.000000  0.009346  0.004895   
4263      399.0         63.0   0.001667  ...  0.000000  0.006667  0.008750   

         f_e_6     f_e_7  f_e_8     f_e_9    f_e_10  f_e_11  richness  
0     0.000000  0.000000    0.0  0.000000  0.000000     0.0  1.000000  
1     0.000000  0.002298    0.0  0.000718  0.000718     0.0  0.482127  
2     0.000434  0.000868    0.0  0.000217  0.000217     0.0  0.459709  
3     0.000000  0.002310    0.0  0.000577  0.000577     0.0  0.406890  
4     0.000000  0.003756    0.0  0.000417  0.000417     0.0  0.542894  
...        ...       ...    ...       ... 

In [ ]:
df = df.dropna()
df.shape

(4262, 60)

In [ ]:
T1 = ' '.join(df['T1'].values)
list_bigram = return_best_bi_grams(T1)
list_trigram = return_best_tri_grams(T1)
T2 = ' '.join(df['T2'].values)
list_bigram = return_best_bi_grams(T2)
list_trigram = return_best_tri_grams(T2)

In [ ]:
ind = train_test_split(df[['T1', 'T2', 'class']], test_size=0.2, stratify=df['class'])
ind_train = list(ind[0].index)
ind_test = list(ind[1].index)

In [ ]:
nlp_train = df.loc[ind_train]
nlp_test = df.loc[ind_test]

In [ ]:
# Training TF-IDF

In [ ]:
vectorize = TfidfVectorizer()
X_train = vectorize.fit_transform(nlp_train['text_tfidf'])
X_test = vectorize.transform(nlp_test['text_tfidf'])

clf = LogisticRegression(random_state=0).fit(X_train, nlp_train['class'].astype('int'))
y_pred = clf.predict(X_test)

score_lr = accuracy_score(nlp_test['class'].astype('int'), y_pred)
f1_lr = f1_score(nlp_test['class'].astype('int'), y_pred, average="macro")

# plot_confusion_matrix_from_data(nlp_test['label'].astype('int'), y_pred)

print("Training done, accuracy is : ", score_lr)
print("Training done, f1-score is : ", f1_lr)
confusion_matrix(nlp_test['class'].astype('int'), y_pred)

Training done, accuracy is :  0.2708089097303634
Training done, f1-score is :  0.2705191662541935


array([[107, 320],
       [302, 124]])

In [ ]:
# def plot_confusion_matrix_from_data(y_test, predictions, columns=None, annot=True, cmap="Oranges",
#       fmt='.2f', fz=11, lw=0.5, cbar=False, figsize=[8,8], show_null_values=0, pred_val_axis='lin'):
#     """
#         plot confusion matrix function with y_test (actual values) and predictions (predic),
#         whitout a confusion matrix yet
#     """
#     from sklearn.metrics import confusion_matrix
#     from pandas import DataFrame

#     #data
#     if(not columns):
#         #labels axis integer:
#         ##columns = range(1, len(np.unique(y_test))+1)
#         #labels axis string:
#         from string import ascii_uppercase
#         columns = ['class %s' %(i) for i in list(ascii_uppercase)[0:len(np.unique(y_test))]]

In [ ]:
#Training Random Forest

In [ ]:
clf = RandomForestClassifier(random_state=42,n_estimators=150,n_jobs=-1).fit(X_train, nlp_train['class'].astype('int'))
y_pred = clf.predict(X_test)

score_lr = accuracy_score(nlp_test['class'].astype('int'), y_pred)
f1_lr = f1_score(nlp_test['class'].astype('int'), y_pred, average="macro")

# plot_confusion_matrix_from_data(nlp_test['label'].astype('int'), y_pred)

print("Training done, accuracy is : ", score_lr)
print("Training done, f1-score is : ", f1_lr)
confusion_matrix(nlp_test['class'].astype('int'), y_pred)

Training done, accuracy is :  0.2696365767878077
Training done, f1-score is :  0.26915042117930205


array([[126, 301],
       [322, 104]])

In [ ]:
clf = xgb.XGBClassifier().fit(X_train, nlp_train['class'].astype('int'))
y_pred = clf.predict(X_test)

score_lr = accuracy_score(nlp_test['class'].astype('int'), y_pred)
f1_lr = f1_score(nlp_test['class'].astype('int'), y_pred, average="macro")

# plot_confusion_matrix_from_data(nlp_test['class'].astype('int'), y_pred)

print("Training done, accuracy is : ", score_lr)
print("Training done, f1-score is : ", f1_lr)
# confusion_matrix(nlp_test['class'].astype('int'), y_pred)

Training done, accuracy is :  0.25908558030480655
Training done, f1-score is :  0.2588563949715693


In [ ]:
from sklearn.svm import SVC
clf = SVC().fit(X_train, nlp_train['class'].astype('int'))
y_pred = clf.predict(X_test)

score_lr = accuracy_score(nlp_test['class'].astype('int'), y_pred)
f1_lr = f1_score(nlp_test['class'].astype('int'), y_pred, average="macro")

# plot_confusion_matrix_from_data(nlp_test['label'].astype('int'), y_pred)

print("Training done, accuracy is : ", score_lr)
print("Training done, f1-score is : ", f1_lr)
confusion_matrix(nlp_test['class'].astype('int'), y_pred)

Training done, accuracy is :  0.25791324736225085
Training done, f1-score is :  0.25771329354850686


array([[117, 310],
       [323, 103]])

In [ ]:
from sklearn.naive_bayes import BernoulliNB
clf = SVC().fit(X_train, nlp_train['class'].astype('int'))
y_pred = clf.predict(X_test)

score_lr = accuracy_score(nlp_test['class'].astype('int'), y_pred)
f1_lr = f1_score(nlp_test['class'].astype('int'), y_pred, average="macro")

# plot_confusion_matrix_from_data(nlp_test['class'].astype('int'), y_pred)

print("Training done, accuracy is : ", score_lr)
print("Training done, f1-score is : ", f1_lr)
confusion_matrix(nlp_test['class'].astype('int'), y_pred)

In [ ]:
# Training BERT

In [ ]:
model = ClassificationModel('bert', 'bert-base-cased', num_labels=2, args={'reprocess_input_data': True, 'overwrite_output_dir': True,  'num_train_epochs' : 15}, use_cuda=True) 
model.train_model(nlp_train[['T1', 'class']])
model.train_model(nlp_train[['T2', 'class']])
predictions_T1, raw_outputs_T1 = model.predict(list(nlp_test['T1']))
predictions_T2, raw_outputs_T2 = model.predict(list(nlp_test['T2']))
score_bert = accuracy_score(predictions_T1, nlp_test['class'])
f1_bert = f1_score(predictions_T1, nlp_test['class'], average="macro")
predictions, raw_out_train = model.predict(list(nlp_train['text']))
print("Training done, accuracy is : ", score_bert)
print("Training done, f1-score is : ", f1_bert)
score_bert = accuracy_score(predictions, nlp_test['label'])
f1_bert = f1_score(predictions, nlp_test['label'], average="macro")
predictions, raw_out_train = model.predict(list(nlp_train['text']))
print("Training done, accuracy is : ", score_bert)
print("Training done, f1-score is : ", f1_bert)

In [ ]:
predictions, raw_outputs = model.predict(list(nlp_test['text']))
score_bert = accuracy_score(predictions, nlp_test['label'])
f1_bert = f1_score(predictions, nlp_test['label'], average="macro")
predictions, raw_out_train = model.predict(list(nlp_train['text']))
print("Training done, accuracy is : ", score_bert)
print("Training done, f1-score is : ", f1_bert)

  0%|          | 0/594 [00:00<?, ?it/s]

  0%|          | 0/75 [00:00<?, ?it/s]

  0%|          | 0/2389 [00:00<?, ?it/s]

  0%|          | 0/299 [00:00<?, ?it/s]

Training done, accuracy is :  0.9393939393939394
Training done, f1-score is :  0.9393602540834847


In [ ]:
#Training Style Classifier

In [ ]:
X_style_train = nlp_train[["avg_len", "num_short_w", "per_digit", "per_cap", "f_a", "f_b", "f_c", "f_d", "f_e", "f_f", "f_g", "f_h", "f_i", "f_j", "f_k", "f_l", "f_m", "f_n", "f_o", "f_p", "f_q", "f_r", "f_s", "f_t", "f_u", "f_v", "f_w", "f_x", "f_y", "f_z", "f_0", "f_1", "f_2", "f_3", "f_4", "f_5", "f_6", "f_7", "f_8", "f_9", "f_e_0", "f_e_1", "f_e_2", "f_e_3", "f_e_4", "f_e_5", "f_e_6", "f_e_7", "f_e_8", "f_e_9", "f_e_10", "f_e_11", "richness",]]# "CC", "CD", "DT", "EX", "FW", "IN", "JJ", "JJR", "JJS", "LS", "MD", "NN", "NNS", "NNP", "PDT", "POS", "PRP", "PRPs", "RB", "RBR", "RBS", "RP", "SYM", "TO", "UH", "VB", "VBD", "VBG", "VBN", "VBP", "VBZ", "WDT", "WP", "WPs", "WRB",  ]]
X_style_test = nlp_test[["avg_len", "num_short_w", "per_digit", "per_cap", "f_a", "f_b", "f_c", "f_d", "f_e", "f_f", "f_g", "f_h", "f_i", "f_j", "f_k", "f_l", "f_m", "f_n", "f_o", "f_p", "f_q", "f_r", "f_s", "f_t", "f_u", "f_v", "f_w", "f_x", "f_y", "f_z", "f_0", "f_1", "f_2", "f_3", "f_4", "f_5", "f_6", "f_7", "f_8", "f_9", "f_e_0", "f_e_1", "f_e_2", "f_e_3", "f_e_4", "f_e_5", "f_e_6", "f_e_7", "f_e_8", "f_e_9", "f_e_10", "f_e_11", "richness",]]# "CC", "CD", "DT", "EX", "FW", "IN", "JJ", "JJR", "JJS", "LS", "MD", "NN", "NNS", "NNP", "PDT", "POS", "PRP", "PRPs", "RB", "RBR", "RBS", "RP", "SYM", "TO", "UH", "VB", "VBD", "VBG", "VBN", "VBP", "VBZ", "WDT", "WP", "WPs", "WRB", ]]

clf = xgb.XGBClassifier().fit(X_style_train, nlp_train['class'])
# clf = LogisticRegression(random_state=0).fit(X_style_train, nlp_train['class'])
y_pred = clf.predict(X_style_test)
y_proba = clf.predict_proba(X_style_test)
y_proba_train = clf.predict_proba(X_style_train)
score_style = accuracy_score(nlp_test['class'], y_pred)
f1_style = f1_score(nlp_test['class'], y_pred, average="macro")

print("Training done, accuracy is : ", score_style)
print("Training done, f1-score is : ", f1_style)
confusion_matrix(nlp_test['class'], y_pred)

Training done, accuracy is :  0.28722157092614303
Training done, f1-score is :  0.2871970796499098


array([[125, 302],
       [306, 120]])

In [ ]:
#Model Combination

In [ ]:
feat_for_BERT_LR_train = np.concatenate([raw_out_train, y_proba_train], axis=1)
feat_for_BERT_LR_test = np.concatenate([raw_outputs, y_proba], axis=1)

# clf = LogisticRegression(random_state=0).fit(feat_for_BERT_LR_train, nlp_train['label'])
clf = xgb.XGBClassifier().fit(feat_for_BERT_LR_train, nlp_train['label'])

y_pred = clf.predict(feat_for_BERT_LR_test)
score_comb = accuracy_score(nlp_test['label'], y_pred)
f1_comb = f1_score(nlp_test['label'], y_pred, average="macro")

print("Training done, accuracy is : ", score_comb)
print("Training done, f1-score is : ", f1_comb)
confusion_matrix(nlp_test['label'], y_pred)

# plot_confusion_matrix_from_data(nlp_test['Target'], y_pred)

Training done, accuracy is :  0.9393939393939394
Training done, f1-score is :  0.9393602540834847


array([[272,  24],
       [ 12, 286]])

In [ ]:
#Character n-gram

In [ ]:
feats_train = nlp_train['text'].apply(lambda x: find_freq_n_gram_in_txt(x, list_bigram, list_trigram)).values
feats_test = nlp_test['text'].apply(lambda x: find_freq_n_gram_in_txt(x, list_bigram, list_trigram)).values

feats_train = pd.DataFrame(feats_train)[0].apply(lambda x: pd.Series(x))
feats_test = pd.DataFrame(feats_test)[0].apply(lambda x: pd.Series(x))

clf_char = xgb.XGBClassifier().fit(feats_train, nlp_train['label'])
# clf_char = LogisticRegression(random_state=0).fit(feats_train, nlp_train['label'])
y_pred = clf_char.predict(feats_test)
y_proba = clf_char.predict_proba(feats_test)
y_proba_train = clf_char.predict_proba(feats_train)

score_char = accuracy_score(nlp_test['label'], y_pred)
f1_char = f1_score(nlp_test['label'], y_pred, average="macro")

print("Training done, accuracy is : ", score_char)
print("Training done, f1-score is : ", f1_char)
confusion_matrix(nlp_test['label'], y_pred)

Training done, accuracy is :  0.9006734006734006
Training done, f1-score is :  0.9005919778072143


array([[259,  37],
       [ 22, 276]])

In [ ]:
#BERT + Style + Char N-gram

In [ ]:
feat_for_BERT_full_train = np.concatenate([feat_for_BERT_LR_train, y_proba_train], axis=1)
feat_for_BERT_full_test = np.concatenate([feat_for_BERT_LR_test, y_proba], axis=1)

clf = xgb.XGBClassifier().fit(feat_for_BERT_full_train, nlp_train['label'])
# clf = LogisticRegression(random_state=0).fit(feat_for_BERT_full_train, nlp_train['label'])

y_pred = clf.predict(feat_for_BERT_full_test)
score_comb_fin = accuracy_score(nlp_test['label'], y_pred)
f1_comb_fin = f1_score(nlp_test['label'], y_pred, average="macro")
print("Training done, accuracy is : ", score_comb_fin)
print("Training done, f1-score is : ", f1_comb_fin)
confusion_matrix(nlp_test['label'], y_pred)

list_scores, list_f1 = [] , []
list_scores.append([score_lr, score_bert, score_style, score_comb])
list_f1.append([f1_lr, f1_bert, f1_style, f1_comb])


Training done, accuracy is :  0.9393939393939394
Training done, f1-score is :  0.9393602540834847


In [ ]:
confusion_matrix(nlp_test['label'], y_pred)

array([[272,  24],
       [ 12, 286]])

In [ ]:
raw_out_train

array([[-5.46875   ,  6.22265625],
       [ 5.17578125, -5.83203125],
       [ 5.03125   , -5.99609375],
       ...,
       [-5.4765625 ,  6.21875   ],
       [ 5.171875  , -5.91796875],
       [-5.47265625,  6.23046875]])

In [ ]:
raw_outputs

array([[-5.296875  ,  6.03125   ],
       [-5.484375  ,  6.22265625],
       [ 5.07421875, -5.984375  ],
       ...,
       [-5.48828125,  6.21484375],
       [ 5.15234375, -5.96875   ],
       [-5.46875   ,  6.23046875]])

In [ ]:
np.save(path+'raw_outputs_bert_p2.npy', raw_outputs)

In [ ]:
np.save(path+'raw_out_train_bert_p2.npy', raw_out_train)

In [ ]:
# df.to_csv('p2_ling.csv')